"""The generated results block in the sentiment project README (numbers from results.json)."""

from pathlib import Path

from dap.common import generated, paths

START = (
    "<!-- results:start (generated by `dap sentiment train` "
    "from reports/sentiment/results.json) -->"
)
END = "<!-- results:end -->"
ORDER = (
    "vader_default",
    "vader_tuned",
    "tfidf_logistic",
    "roberta",
    "roberta_tuned",
    "roberta_calibrated",
    "finetuned",
)
# The models the per-class table covers: every RoBERTa variant, plus the fine-tuned one for scale
PER_CLASS = ("roberta", "roberta_tuned", "roberta_calibrated", "finetuned")


def readme_path() -> Path:
    return paths.repo_root() / "projects" / "sentiment-analysis" / "README.md"


def _ci(x: dict) -> str:
    return f"{x['estimate']:.3f} ({x['ci_low']:.3f} to {x['ci_high']:.3f})"


def difference(diffs: dict, a: str, b: str) -> dict:
    """a minus b, whichever order the bootstrap stored the pair in."""
    if f"{a} minus {b}" in diffs:
        return diffs[f"{a} minus {b}"]
    x = diffs[f"{b} minus {a}"]
    return {"estimate": -x["estimate"], "ci_low": -x["ci_high"], "ci_high": -x["ci_low"]}


def render(r: dict) -> str:
    d = r["data"]
    share = d["eval_label_share"]
    lines = [
        START,
        "",
        f"**Data:** {d['reviews']:,} reviews; {d['after_dedupe']:,} after removing duplicates; "
        f"split by reviewer into {d['train_reviews']:,} training, {d['validation_reviews']:,} "
        f"validation and {d['test_reviews']:,} test reviews. Every model is scored on the same "
        f"{d['eval_sample']:,} test reviews ({share['positive']:.0%} positive, "
        f"{share['negative']:.0%} negative, {share['neutral']:.0%} neutral). Intervals are 95% "
        f"paired bootstrap intervals ({r['settings']['bootstrap_resamples']:,} resamples).",
        "",
        "| Model | Macro-F1 (95% interval) | Accuracy | Neutral recall | Negative recall |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for m in ORDER:
        x = r["models"][m]
        pc = x["per_class"]
        lines.append(
            f"| {x['label']} | {_ci(x['macro_f1'])} | {x['accuracy']:.3f} | "
            f"{pc['neutral']['recall']:.2f} | {pc['negative']['recall']:.2f} |"
        )
    diffs = r["differences"]
    lines += [
        "",
        "Differences in macro-F1 (same reviews, paired bootstrap):",
        "",
    ]
    for a, b in (
        ("roberta", "vader_default"),
        ("tfidf_logistic", "roberta"),
        ("vader_tuned", "vader_default"),
        ("roberta_tuned", "roberta"),
        ("tfidf_logistic", "roberta_tuned"),
        ("roberta_calibrated", "roberta"),
        ("roberta_calibrated", "roberta_tuned"),
        ("finetuned", "roberta"),
        ("finetuned", "tfidf_logistic"),
    ):
        names = f"{r['models'][a]['label']} minus {r['models'][b]['label']}"
        lines.append(f"- {names}: {_ci(difference(diffs, a, b))}")
    lines += [
        "",
        "Per class, for the RoBERTa variants and the fine-tuned model (precision / recall / F1):",
        "",
        "| Model | Negative | Neutral | Positive |",
        "| --- | --- | --- | --- |",
    ]
    for m in PER_CLASS:
        pc = r["models"][m]["per_class"]
        cells = [
            f"{pc[c]['precision']:.2f} / {pc[c]['recall']:.2f} / {pc[c]['f1']:.2f}"
            for c in ("negative", "neutral", "positive")
        ]
        lines.append(f"| {r['models'][m]['label']} | {' | '.join(cells)} |")
    s = r["settings"]
    off, grid = s["roberta_tuned_log_offsets"], s["roberta_offset_grid"]
    edge = (
        "inside the grid, not on its edge"
        if s["roberta_offsets_inside_grid"]
        else "on the edge of the grid, so the grid should be wider"
    )
    lines += [
        "",
        f"The tuned rule adds {off['negative']:+.1f} to the log probability of negative and "
        f"{off['neutral']:+.1f} to neutral, picked from a grid of {grid['low']:g} to "
        f"{grid['high']:g} in steps of {grid['step']:g} on {s['roberta_tuning_reviews']:,} "
        f"validation reviews "
        f"(the best pair is {edge}). The recalibration is a logistic regression on RoBERTa's three "
        f"log probabilities, fitted on the same reviews, with "
        f"{'balanced' if s['roberta_calibrated_class_weight'] == 'balanced' else 'equal'} "
        f"class weights (picked by 5-fold cross-validation inside them).",
        "",
        END,
    ]
    return "\n".join(lines)


def update(results: dict, path: Path | None = None) -> bool:
    return generated.replace_block(Path(path or readme_path()), START, END, render(results))


def current_block(path: Path | None = None) -> str:
    return generated.current_block(Path(path or readme_path()), START, END)
