"""The generated results block in the sentiment project README (numbers from results.json)."""

from pathlib import Path

from dap.common import generated, paths

START = (
    "<!-- results:start (generated by `dap sentiment train` "
    "from reports/sentiment/results.json) -->"
)
END = "<!-- results:end -->"
ORDER = ("vader_default", "vader_tuned", "tfidf_logistic", "roberta")


def readme_path() -> Path:
    return paths.repo_root() / "projects" / "sentiment-analysis" / "README.md"


def _ci(x: dict) -> str:
    return f"{x['estimate']:.3f} ({x['ci_low']:.3f} to {x['ci_high']:.3f})"


def difference(diffs: dict, a: str, b: str) -> dict:
    """a minus b, whichever order the bootstrap stored the pair in."""
    if f"{a} minus {b}" in diffs:
        return diffs[f"{a} minus {b}"]
    x = diffs[f"{b} minus {a}"]
    return {"estimate": -x["estimate"], "ci_low": -x["ci_high"], "ci_high": -x["ci_low"]}


def render(r: dict) -> str:
    d = r["data"]
    share = d["eval_label_share"]
    lines = [
        START,
        "",
        f"**Data:** {d['reviews']:,} reviews; {d['after_dedupe']:,} after removing duplicates; "
        f"split by reviewer into {d['train_reviews']:,} training, {d['validation_reviews']:,} "
        f"validation and {d['test_reviews']:,} test reviews. Every model is scored on the same "
        f"{d['eval_sample']:,} test reviews ({share['positive']:.0%} positive, "
        f"{share['negative']:.0%} negative, {share['neutral']:.0%} neutral). Intervals are 95% "
        f"paired bootstrap intervals ({r['settings']['bootstrap_resamples']:,} resamples).",
        "",
        "| Model | Macro-F1 (95% interval) | Accuracy | Neutral recall | Negative recall |",
        "| --- | --- | ---: | ---: | ---: |",
    ]
    for m in ORDER:
        x = r["models"][m]
        pc = x["per_class"]
        lines.append(
            f"| {x['label']} | {_ci(x['macro_f1'])} | {x['accuracy']:.3f} | "
            f"{pc['neutral']['recall']:.2f} | {pc['negative']['recall']:.2f} |"
        )
    diffs = r["differences"]
    lines += [
        "",
        "Differences in macro-F1 (same reviews, paired bootstrap):",
        "",
    ]
    for a, b in (
        ("roberta", "vader_default"),
        ("tfidf_logistic", "roberta"),
        ("vader_tuned", "vader_default"),
    ):
        names = f"{r['models'][a]['label']} minus {r['models'][b]['label']}"
        lines.append(f"- {names}: {_ci(difference(diffs, a, b))}")
    lines += ["", END]
    return "\n".join(lines)


def update(results: dict, path: Path | None = None) -> bool:
    return generated.replace_block(Path(path or readme_path()), START, END, render(results))


def current_block(path: Path | None = None) -> str:
    return generated.current_block(Path(path or readme_path()), START, END)
