"""The generated results block in the project README.

Every number in the README comes from `reports/results.json` through `render`. The block sits
between two HTML comment markers; `dap health train` rewrites it, and a test fails if it's stale.
"""

import re
from pathlib import Path

from dap.common import paths
from dap.health.models import MODELS

START = "<!-- results:start (generated by `dap health train` from reports/results.json) -->"
END = "<!-- results:end -->"
_BLOCK = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)


def readme_path() -> Path:
    return paths.repo_root() / "projects" / "avoidable-hospitalisations" / "README.md"


STATE_SHORT = {
    "New South Wales": "NSW",
    "Victoria": "Vic.",
    "Queensland": "Qld",
    "South Australia": "SA",
    "Western Australia": "WA",
    "Tasmania": "Tas.",
    "Northern Territory": "NT",
    "Australian Capital Territory": "ACT",
}


def _area(x: dict) -> str:
    return f"{x['sa3']}, {STATE_SHORT.get(x['state'], x['state'])} ({_pct(x['pct_vs_expected'])})"


def _pct(x: float) -> str:
    return f"{x:+.0f}%"


def render(r: dict) -> str:
    t, a, res = r["target"], r["spatial_autocorrelation"], r["residuals"]
    lines = [
        START,
        "",
        f"**Data:** {t['areas']} SA3s in {t['sa4_groups']} SA4s, {t['features']} input features, "
        f"target year {t['year']}. Cross-validation: {r['cv']['folds']} folds, repeated "
        f"{r['cv']['repeats']} times. R² and MAE are on the rate scale (admissions per 100,000), "
        "weighted by population.",
        "",
        "| Model | R², SA4s held out | R², random folds | Gap | MAE, SA4s held out | R² on log scale, SA4s held out |",  # noqa: E501
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    for cls in MODELS:
        m = r["models"][cls.name]
        sp, rd = m["spatial"], m["random"]
        lines.append(
            f"| {m['label']} | {sp['r2']['mean']:.2f} | {rd['r2']['mean']:.2f} | "
            f"{m['optimism_r2']:.2f} | {sp['mae']['mean']:,.0f} | {sp['r2_log']['mean']:.2f} |"
        )
    lag = r["interpretation"]["spatial_lag"]
    above = res["most_above_expected"][:5]
    below = res["most_below_expected"][:5]
    states = sorted(res["pct_vs_expected_by_state"].items(), key=lambda kv: -kv[1])
    lines += [
        "",
        f"- Global Moran's I of the log rate: **{a['moran_log_pph']['I']:.2f}** "
        f"(permutation p = {a['moran_log_pph']['p_sim']}). LISA finds "
        f"{a['lisa_clusters']['High-high']} hot-spot and {a['lisa_clusters']['Low-low']} "
        "cold-spot SA3s.",
        "- Spatial lag model, R² on the log scale. Fitted on every area: "
        f"{lag['r2_log_in_sample_with_neighbour_rates']:.2f} using the neighbours' observed rates "
        f"(residual Moran's I {lag['residual_moran_I']:.2f}), "
        f"{lag['r2_log_in_sample_features_only']:.2f} from features alone. With whole SA4s held "
        "out: "
        f"{r['models']['spatial_lag']['spatial']['r2_log']['mean']:.2f} and residual Moran's I "
        f"{r['models']['spatial_lag']['residual_moran_I']:.2f}.",
        f"- Residual map model: {r['models'][res['model']]['label']}. "
        f"{res['share_of_population_within_10pct']:.0%} of people live in an SA3 within 10% of "
        f"its expected rate. Moran's I of the log residual: {res['moran_log_ratio']['I']:.2f}.",
        "- Most above expected: " + "; ".join(_area(x) for x in above) + ".",
        "- Most below expected: " + "; ".join(_area(x) for x in below) + ".",
        "- By state (population-weighted): " + ", ".join(f"{s} {_pct(v)}" for s, v in states) + ".",
        "",
        END,
    ]
    return "\n".join(lines)


def update(results: dict, path: Path | None = None) -> bool:
    """Replace the block in the README. Returns True if the file changed."""
    path = Path(path or readme_path())
    text = path.read_text(encoding="utf-8")
    if not _BLOCK.search(text):
        raise ValueError(f"{path} has no generated results block")
    new = _BLOCK.sub(lambda _m: render(results), text)
    if new != text:
        path.write_text(new, encoding="utf-8", newline="\n")
    return new != text


def current_block(path: Path | None = None) -> str:
    m = _BLOCK.search(Path(path or readme_path()).read_text(encoding="utf-8"))
    return m.group(0) if m else ""
