"""Regenerate the synthetic test fixtures: `uv run python tests/fixtures/make_fixtures.py`.

Everything here is made up: ten square "SA3" areas in three "SA4" groups (codes 991, 992 and
993, which no real SA4 uses), a target table with one suppressed area, a feature table, a tiny
MyHospitals-shaped JSON file, and a manifest that points at them with `file:` URLs so fetch can be
tested offline.
"""

import json
from pathlib import Path

import geopandas as gpd
import numpy as np
import pandas as pd
import yaml
from shapely.geometry import box

from dap.common.manifest import sha256_file
from dap.common.seeds import set_seed

HERE = Path(__file__).resolve().parent
CRS = "EPSG:7844"  # GDA2020, the ABS boundary CRS
SA4_OF = ["991"] * 4 + ["992"] * 3 + ["993"] * 3


def make_areas(rng: np.random.Generator) -> gpd.GeoDataFrame:
    rows = []
    for i, sa4 in enumerate(SA4_OF):
        x0, y0 = 150.0 + (i % 5) * 0.1, -34.0 - (i // 5) * 0.1
        rows.append(
            {
                "sa3_code": f"{sa4}{i + 1:02d}",
                "sa3_name": f"Synthetic area {i + 1}",
                "sa4_code": sa4,
                "state_code": "9",
                "erp": int(rng.integers(20_000, 150_000)),
                "geometry": box(x0, y0, x0 + 0.1, y0 + 0.1),
            }
        )
    return gpd.GeoDataFrame(rows, crs=CRS)


def make_target(areas: gpd.GeoDataFrame, rng: np.random.Generator) -> pd.DataFrame:
    asr = rng.normal(2500, 400, len(areas)).round()
    df = pd.DataFrame(
        {
            "sa3_code": areas.sa3_code,
            "year": "2023-24",
            "asr_per_100k": asr.astype(int).astype(str),
            "count": (asr * areas.erp / 100_000).round().astype(int).astype(str),
            "erp": areas.erp,
        }
    )
    df.loc[df.index[-1], ["asr_per_100k", "count"]] = "n.p."  # one suppressed area, as in AIHW
    return df


def make_features(areas: gpd.GeoDataFrame, rng: np.random.Generator) -> pd.DataFrame:
    n = len(areas)
    return pd.DataFrame(
        {
            "sa3_code": areas.sa3_code,
            "irsd_score": rng.normal(1000, 60, n).round(1),
            "unemployed_pct": rng.uniform(2, 9, n).round(1),
            "age_65_plus_pct": rng.uniform(10, 30, n).round(1),
            "no_motor_vehicle_pct": rng.uniform(2, 15, n).round(1),
            "gp_services_per_100": rng.uniform(400, 800, n).round(1),
        }
    )


def make_reporting_units() -> dict:
    def unit(code, kind, closed=False, private=False, lat=-34.05, lon=150.05):
        return {
            "reporting_unit_code": code,
            "reporting_unit_name": f"Synthetic {code}",
            "reporting_unit_type": {"reporting_unit_type_code": kind},
            "closed": closed,
            "private": private,
            "latitude": lat,
            "longitude": lon,
        }

    return {
        "result": [
            unit("H9001", "H"),
            unit("H9002", "H", private=True),
            unit("H9003", "H", closed=True),
            unit("H9004", "H", lat=None, lon=None),
            unit("LHN901", "LHN"),
        ]
    }


def main() -> None:
    rng = set_seed()
    areas = make_areas(rng)
    areas.to_file(HERE / "areas.gpkg", layer="sa3", driver="GPKG")
    make_target(areas, rng).to_csv(HERE / "target.csv", index=False, lineterminator="\n")
    make_features(areas, rng).to_csv(HERE / "features.csv", index=False, lineterminator="\n")
    units = make_reporting_units()
    (HERE / "reporting_units.json").write_text(
        json.dumps(units, indent=1) + "\n", encoding="utf-8", newline="\n"
    )

    target = HERE / "target.csv"
    manifest = {
        "version": 1,
        "sources": [
            {
                "id": "fixture_target",
                "title": "Synthetic target table",
                "url": "file:target.csv",
                "file": "target.csv",
                "bytes": target.stat().st_size,
                "sha256": sha256_file(target),
                "licence": "CC0 (synthetic)",
            },
            {
                "id": "myhospitals_reporting_units",
                "title": "Synthetic MyHospitals reporting units",
                "url": "file:reporting_units.json",
                "file": "reporting_units.json",
                "volatile": True,
                "expect": {
                    "reporting_units": 5,
                    "hospitals": 4,
                    "hospitals_open_public": 2,
                    "hospitals_missing_coordinates": 1,
                    "tolerance_pct": 0,
                },
                "licence": "CC0 (synthetic)",
            },
        ],
    }
    with (HERE / "manifest.yaml").open("w", encoding="utf-8", newline="\n") as f:
        f.write("# Generated by make_fixtures.py. Synthetic data for tests only.\n")
        yaml.safe_dump(manifest, f, sort_keys=False)


if __name__ == "__main__":
    main()
